osa1/tiny

- src/lib.rs
- src/tui/messaging.rs
- src/tui/mod.rs
- src/tui/tabbed.rs
> Added /ignore to ignore join/quit messages

- src/trie.rs
Garbage collection, and a simple speed up.
> Trie enhancement

- README.md
- pkg/archlinux/PKGBUILD
@osa1 this is my first time using git. Hopefully I am doing this correctly.
I will to change the PKGBUILD's `# Maintainer: Nick Econopouly <wry@mm.st>` line to your contact information after making this pull request, just to see how Github handles the change.
> Aur pkgbuild

- README.md
- src/cmd.rs
- src/config.rs
- src/lib.rs
- src/tui/mod.rs
- src/tui/statusline.rs
- src/tui/tab.rs
I needed the `statusline` piece from #109 . But I was having a lot of trouble merging the current master to that branch. So I rewrote it on top of the current master.
> Statusline implementation

- CHANGELOG.md
- libtiny_tui/src/tui.rs
> tui: Scroll left when there's room in tab bar after closing tabs

- termbox/src/lib.rs
Front and back buffer's CellBuf.w and CellBuf.h fields are always the
same as Termbox.term_width and Termbox.term_height. Remove those and use
self.term_width, self.term_height.
> termbox: Remove redundant CellBuf fields

- libtiny_tui/src/tests/mod.rs
- libtiny_tui/src/tui.rs
- termbox/src/lib.rs
This will allow us testing resizing e.g. in #183.
cc @trevarj
> tui: Implement methods for testing resizing

- libtiny_logger/src/lib.rs
- libtiny_tui/examples/chat.rs
- libtiny_tui/examples/completion.rs
- libtiny_tui/examples/tabs.rs
- libtiny_tui/src/lib.rs
- libtiny_tui/src/tab.rs
- libtiny_tui/src/tests/mod.rs
- libtiny_tui/src/tui.rs
- libtiny_ui/src/lib.rs
- tiny/config.yml
- tiny/src/cmd.rs
- tiny/src/config.rs
- tiny/src/main.rs
Prototyping this...seems to work, but didn't fully test yet.
> Allow server alias in config #186

- libtiny_tui/src/input_area/input_line.rs
- libtiny_tui/src/input_area/mod.rs
- libtiny_tui/src/lib.rs
- libtiny_tui/src/messaging.rs
- libtiny_tui/src/msg_area/mod.rs
- libtiny_tui/src/tests/mod.rs
- libtiny_tui/src/tui.rs
Closes #101 
See #183 for conversation history.
> Text field refactor - word wrap support

- libtiny_tui/src/input_area/input_line.rs
- libtiny_tui/src/input_area/mod.rs
- libtiny_tui/src/messaging.rs
- libtiny_tui/src/tests/mod.rs
First attempt at solving some of the issues on #208
> Caching InputLine calculation. Caching InputArea::height.

- libtiny_tui/src/config.rs
- libtiny_tui/src/messaging.rs
- libtiny_tui/src/msg_area/mod.rs
- libtiny_tui/src/tui.rs
- tiny/config.yml
> Added optional config to limit the number of messages in each tab.

- libtiny_tui/src/tui.rs
- tiny/src/cmd.rs
Since there are two areas for sending commands, in `libtiny_tui` and in the tiny client, I had to add some changes in two areas.
I aligned the /help message because I personally found it difficult to read. I can also imagine a user typing /help and wanting to have the commands printed out nicely so a command can be easily found.
> Added help command (/help).

- Cargo.lock
- libtiny_client/Cargo.toml
- libtiny_client/examples/echo.rs
- libtiny_client/src/lib.rs
- libtiny_client/src/pinger.rs
- libtiny_client/src/state.rs
- libtiny_client/src/stream.rs
- libtiny_tui/Cargo.toml
- libtiny_tui/examples/bench.rs
- libtiny_tui/examples/chat.rs
- libtiny_tui/examples/completion.rs
- libtiny_tui/examples/tabs.rs
- libtiny_tui/examples/text.rs
- libtiny_tui/src/lib.rs
- term_input/Cargo.toml
- term_input/examples/test.rs
- term_input/src/lib.rs
- termbox/Cargo.toml
- termbox/examples/colors.rs
- termbox/examples/input.rs
- termbox/src/lib.rs
- tiny/Cargo.toml
- tiny/src/main.rs
Not ready, tokio-tls still uses old tokio
> Bump tokio to 0.3.3 (from 0.2)

- libtiny_tui/src/config.rs
- libtiny_tui/src/tab.rs
- libtiny_tui/src/tui.rs
- libtiny_ui/src/lib.rs
- tiny/src/conn.rs
> Highlight channels with join/part/quit events. Closed #262

- libtiny_tui/src/msg_area/mod.rs
When a line is removed due to reaching scrollback limit, update the
message area's line height. Added test to assert the height is being
maintained.
Closes #265
> Fixed bug with scrollback limit.

- libtiny_tui/src/messaging.rs
- libtiny_tui/src/tui.rs
Also renamed the function `get_ignore_state` -> `is_showing_status` because it was a bit confusing
Closes #291
> Join/part tab style still worked with /ignore enabled

- term_input/src/lib.rs
> Fixes #295 (backspace didn't work)

- crates/libtiny_tui/src/key_map.rs
- crates/term_input/src/lib.rs
These keys are now available for binding:
- Function keys (F1-F12)
- Ctrl/Alt/Shift + Function keys, ex. `alt_f2`
- Shift + Left/Right Arrow
- Ctrl + \
- Ctrl + ]
- Ctrl + /
Closes #338
> Added extra key support

- README.md
- crates/tiny/src/cmd.rs
- crates/tiny/src/main.rs
- crates/tiny/src/ui.rs
@trevarj I can't add you as a reviewer but it would be great if you could take a look :-)
> Clarify that /reload is for TUI config, fix warnings

- crates/libtiny_client/src/lib.rs
- crates/libtiny_client/src/state.rs
- crates/libtiny_tui/src/input_area/input_line.rs
- crates/libtiny_tui/src/input_area/mod.rs
- crates/libtiny_tui/src/key_map.rs
- crates/libtiny_tui/src/tab.rs
- crates/libtiny_tui/src/tui.rs
- crates/term_input/src/lib.rs
- crates/tiny/src/cmd.rs
- crates/tiny/src/conn.rs
- crates/tiny/src/ui.rs
> Fixed some clippy warnings

- .github/workflows/ci.yml
- crates/libtiny_tui/src/tests/config.rs
Also updates CI configs.
Fixes #407.
> Fix tab config test with desktop-notifications feature
