osa1/tiny

src/logger.rs
Fix #36 
I think this is not the best approach.  `fs::create_dir_all` may still fails in many scenario, so returning a `Result` may be better.  But that still need more work.
=> Deep create log dir

CHANGELOG.md, README.md, src/lib.rs, src/tui/mod.rs, src/tui/tabbed.rs
This is something I use personally.
You can now use `/switch` command to switch to the window with a
specific substring.
> Don't know if its he right command name ( `goto` may be better )
Usage:
```
/switch freenode
```
=> Add switch command

CHANGELOG.md, src/tui/text_field.rs, term_input/src/lib.rs
Fix #41 
@osa1 metioned in the issue
> Map byte string [ 27, 91, 80 ] to to Del
But I found that it doesn't work.  What really works is [27, 91, 51, 126].  Yes I am in TERM=xterm-256color.
```
sh-4.4$ TERM=xterm tput kdch1 | sed -n l
\033[3~$
```
Which represent [27, 92, 91, 126] (ignore the $)
Is [ 27, 91, 80 ] really necessary in some other computer?  If yes I will add it as `XTERM_DEL_2`.
=> Handle Del key

src/lib.rs
Fix #46.  This enable autocomplation on those nicks with prefix.
In current state we have no way to know which user is operator.  We may add that feature later, if that is important.
=> Remove all prefixes in nicks

.travis.yml, CHANGELOG.md, Cargo.toml, README.md, src/cmd.rs, src/lib.rs, src/notifier.rs, src/tui/messaging.rs, src/tui/mod.rs, src/tui/tabbed.rs
for #72 
> By default notifications is set to `mentions`
=> Desktop notifications

CHANGELOG.md, Cargo.toml, src/cmd.rs, src/config.rs, src/conn.rs, src/lib.rs, src/wire.rs
Need to set this in config file, as drafted in https://github.com/osa1/tiny/issues/30#issuecomment-342409032:
``` yaml
servers:                                                                                                                                              
- addr: chat.freenode.net                                                                                                                         
port: 6667                                                                                                                                      
hostname: archlinux                                                                                                                             
realname: Chiu Yue Chun …
```
=> SASL authentication

README.md, pkg/archlinux/PKGBUILD
This resolves #73. When binaries are available the AUR package will be called tiny-irc-client, as there's already a [tiny](https://aur.archlinux.org/packages/tiny).
=> Aur pkgbuild

Cargo.toml, src/lib.rs
This should fix CI. As far as I understand I should still be able to do
`cargo publish` as long as those packages are also published (or maybe
`cargo publish` publishes those for me if they're not? I'm not sure).
=> Use relative paths of term_input and termbox_simple in Cargo.toml

README.md, pkg/archlinux/PKGBUILD
from the README, the PKGBUILD now works out-of-the-box for all users but contains instructions for users with a preferred method of installing the Rust nightly toolchain. I updated the version on the AUR too.
=> updated Arch Linux package and removed dated instructions 

CHANGELOG.md, libtiny_client/src/lib.rs, src/conn.rs
Previously we'd just try the first address, failing that we'd just wait 30 seconds and try again. This caused problems when a user can only connect to some of the addresses (e.g. they can't connect to IPv6 but can connect to IPv4, but the first address returned is IPv6).
Fixes #144
=> When a domain resolves to multiple addrs try all of them

termbox/src/lib.rs
This includes changes in the way Goto's are handled. First, it avoids
printing unnecesary Goto's. Second, it doesn't allocate when it needs to
print them.
This changes allow this termbox version to be as fast as the C version
of termbox.
=> Optimize Goto's

rust-toolchain
Resolves #155 
Hey! This seems to work for me. If I set my default toolchain to `stable`, then I `cd` into the repo directory, `rustup show` yields this:
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/ebroto/.rustup
installed toolchains
--------------------
stable-x86_64-unknown-linux-gnu (default)
beta-x86_64-unknown-linux-gnu
nightly-2019-08-22-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
active toolchain
----------------
nightly-x86_64-unknown-linux-gnu (overridden by '/home/ebroto/src/ebroto-tiny/rust-toolchain')
rustc 1.40.0-nightly (7979016af 2019-10-20)
``` 
Then building with `-vv`:
```
Compiling tiny v0.5.0 (/home/ebroto/src/ebroto-tiny)
Running `CARGO_PKG_VERSION_MINOR=5 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_NAME=tiny CARGO_PKG_DESCRIPTION='An IRC …
```
=> Add a toolchain override file pointing to nightly

CHANGELOG.md, README.md, libtiny_tui/examples/bench.rs, libtiny_tui/src/config.rs, libtiny_tui/src/lib.rs, libtiny_tui/src/messaging.rs, libtiny_tui/src/msg_area/line.rs, libtiny_tui/src/msg_area/mod.rs, libtiny_tui/src/tui.rs, tiny/config.yml, tiny/src/main.rs
Did this during a 11h flight today ..
Here's a screenshot of how this looks when I add `timestamp_format: '%A %H:%M:%S'` to my config file:
This also re-enables the `/reload` command and makes a few other unrelated changes. I'll move those commit to the master branch and rebase this.
The code is not final, it has some bugs. I observed a crash while tweaking the format string and doing `/reload`. There also seems to be issues with splitting lines.
Fixes #159
=> Implement user configurable timestamp formatting

CHANGELOG.md, Cargo.lock, libtiny_client/Cargo.toml, libtiny_client/examples/echo.rs, libtiny_client/src/lib.rs, libtiny_client/src/pinger.rs, libtiny_tui/Cargo.toml, libtiny_tui/examples/bench.rs, libtiny_tui/src/lib.rs, term_input/Cargo.toml, term_input/examples/test.rs, term_input/src/lib.rs, tiny/Cargo.toml, tiny/src/cmd.rs, tiny/src/conn.rs, tiny/src/main.rs, tiny/src/ui.rs
=> Tokio 0.2.7

Cargo.lock, libtiny_client/Cargo.toml, libtiny_client/src/lib.rs, libtiny_client/src/stream.rs, tiny/Cargo.toml
Added a default feature `tls-native` with the status quo, and a non-default feature `tls-rustls` which uses rustls (with rustls-native-certs to use the platform's native cert store).
This also adds a dependency on lazy_static so that the TLS connector is only created once (saves parsing all the certs repeatedly), but lazy_static was already in the dependency tree due to several other packages in the tree depending on it.
=> Optional rustls support

libtiny_tui/src/lib.rs, libtiny_tui/src/tests/mod.rs, libtiny_tui/src/tui.rs, termbox/src/lib.rs
This PR adds a way to test TUI rendering without actually doing any rendering to the terminal. An example test shows how to define a test:
```rust
#[test]
fn init_screen() {
let mut tui = TUI::new_test(20, 10);
tui.draw();
#[rustfmt::skip]
let screen =
"|                    |
|                    |
|                    |
|                    |
|                    |
|                    |
|Any mentions to you |
|will be listed here.|
|                    |
|mentions            |";
expect_screen(screen, &tui);
}
```
This creates a new test instance of the TUI, draws it (not to the terminal, only to termbox's internal buffer), and then compares the screen with the given screen. The screen bounds are marked with `|`s.
There are pretty much no runtime overheads of this addition. Only changes …
=> A framework for TUI tests

.github/workflows/ci.yml, .github/workflows/release.yml, README.md, libtiny_client/Cargo.toml, libtiny_tui/Cargo.toml, libtiny_tui/src/notifier.rs, tiny/Cargo.toml
With this I can make a statically linked executable with
$ cargo build --target=x86_64-unknown-linux-musl \
--no-default-features --features tls-rustls
The generated executable does not support generating desktop
notifications and uses rustls instead of libssl.
(#65)
=> Make desktop notifications feature (dbus) optional

CHANGELOG.md, libtiny_tui/src/lib.rs, libtiny_tui/src/tests/mod.rs, libtiny_tui/src/text_field.rs
Previous buggy behavior shown in the new test.
Other changes:
- expect_screen error reporting improved for easier comparison of expected and seen screens
- expect_screen now takes a caller location for better error reporting
=> Fix a text field bug when updating scroll after C-w

Cargo.lock, Cargo.toml, term_input/Cargo.toml, term_input/src/lib.rs, term_input_macros/Cargo.toml, term_input_macros/src/lib.rs, term_input_macros/src/syntax.rs, term_input_macros/src/tree.rs
Instead of linearly searching through a few dozen of items when a key
combination is pressed, we now generate a more efficient parser with
help of a proc macro for the combination. The generated function looks
at every byte in the input once. As an example of how this works, for
this declaration:
byte_seq_parser! {
example -> Key,
[1, 2] => Key::Del,
[1, 3] => Key::Home,
[0] => Key::PageUp,
}
This is the generated function
fn example(buf: &[u8]) -> Option<(Key, usize)> {
let mut i: usize = 0;
match buf.get(i) {
None => None,
Some(byte) => match byte {
1u8 => {
i += 1;
match buf.get(i) {
None => None,
Some(byte) => match byte {
3u8 => {
i += 1;
Some((Key::Home, i))
}
2u8 => {
i += 1;
Some((Key::Del, i))
}
_ => None,
},
}
}
0u8 => {
i += 1;
Some((Key::PageUp, i))
}
_ => None,
},
}
}
(This …
=> term_input: A more efficient key combination parser

tiny/src/main.rs
Sample log line:
```
[2020-06-02T08:44:00Z] DEBUG [libtiny_logger/src/lib.rs:164] Trying to open log file: "/home/trevor/tiny_logs/chat.freenode.net_#trevsroom.txt"
```
I put brackets around the timestamp and source file path due to personal preference. Let me know if this should be reverted back to having everything in one set of brackets [ ]
Closes #204
=> Added line number to log formatter. Closes #204

libtiny_tui/src/editor.rs, libtiny_tui/src/lib.rs, libtiny_tui/src/tests/mod.rs, libtiny_tui/src/tui.rs, termbox/src/lib.rs
Previously running $EDITOR would block tokio event loop, which causes
all kinds of panics, and timeouts in connections, see #185 as an
example.
We now run $EDITOR in a new thread, and stop reading stdin in the input
handler task during that. Also fixes termbox's suspend method, which
previously keps using tty after suspend.
See also module documentation of `editor`.
Fixes #185
=> Fix $EDITOR support

libtiny_tui/src/input_area/input_line.rs, libtiny_tui/src/lib.rs, libtiny_tui/src/line_split.rs, libtiny_tui/src/msg_area/line.rs, libtiny_tui/src/msg_area/mod.rs
Reused LineDataCache. Basically a drop-in fix. 
I did have to manually go through each of the failing tests, because they weren't accurate to how text should get rendered.
Closes #202
=> Refactored line.rs height calculation and drawing.

libtiny_tui/src/input_area/mod.rs
When pasting a multiline string, specifically when coming back from the editor, we need to call recalculate so the input line is drawn at the correct height, otherwise it will go out of bounds.
Closes #225
=> Fixes panic when pasting a long string.

libtiny_tui/src/msg_area/line.rs, libtiny_tui/src/msg_area/mod.rs, libtiny_tui/src/tests/mod.rs
When multiple users join/part from a channel at the same timestamp, the line gets modified. This wasn't invalidating the height calulation so it was causing an overflow if many people join/part or if your screen is small and it needs to wrap that line after modification.
Ugh, basically what I did for a fix is just add a way to force invalidating the height of the line when it's modified. Didn't think about this when I added `LineDataCache` for height calculation.
Closes #227
=> Fixed join/part line modification panic

libtiny_client/src/state.rs
Falling back to getting the server name from the prefix, since some IRC servers don't comply with the standard. 
Recommended by https://www.irc.com/dev/docs/refs/numerics/002.html
> The \<servername\> may also include other information depending on the server software, for example irc.example.com[203.0.113.15/6667], so we instead recommend relying on the prefix or the RPL_MYINFO (004) numeric if knowing the current server hostname is desired.
Closes #239
=> Fallback to prefix for server name parsing of RPL_YOURHOST reply

CHANGELOG.md, libtiny_client/src/state.rs, libtiny_wire/src/lib.rs, tiny/src/conn.rs
Previously when we see an ambiguous prefix (e.g. "localhost") we'd assume
server. We now have a prefix variant `Ambiguous` for such cases and resolving
the ambiguity is left to the caller.
When there's an ambiguity we try to do the reasonable thing depending on the
type of the message:
- When the message is a numeric reply we assume server.
- In all other cases (e.g. in JOIN/PART/QUIT/PRIVMSG) we assume nick.
Other changes:
- Removed wildcard patterns to make the code future-proof.
- Refactored some logging and comments.
Fixes #247
=> Improve prefix parsing and ambiguous prefix handling

Cargo.lock, libtiny_tui/Cargo.toml, libtiny_tui/benches/bench.rs, libtiny_tui/src/lib.rs, libtiny_tui/src/msg_area/line.rs, libtiny_tui/src/trie.rs, libtiny_tui/src/tui.rs
This removes nightly-only bench setup.
I had to make some TUI modules and methods public to be able to use in benchmarks.
=> Use bencher crate for benchmarks

Cargo.lock, Cargo.toml, libtiny_client/Cargo.toml, libtiny_client/examples/echo.rs, libtiny_client/src/lib.rs, libtiny_client/src/state.rs, libtiny_common/Cargo.toml, libtiny_common/src/lib.rs, libtiny_logger/Cargo.toml, libtiny_logger/src/lib.rs, libtiny_tui/Cargo.toml, libtiny_tui/examples/chat.rs, libtiny_tui/examples/tabs.rs, libtiny_tui/src/lib.rs, libtiny_tui/src/notifier.rs, libtiny_tui/src/tests/mod.rs, libtiny_tui/src/tui.rs, libtiny_ui/Cargo.toml, libtiny_ui/src/lib.rs, libtiny_wire/Cargo.toml, libtiny_wire/src/lib.rs, tiny/Cargo.toml, tiny/src/cmd.rs, tiny/src/conn.rs, tiny/src/main.rs, tiny/src/ui.rs
See the documentation in code for details.
Will fix #248 when complete.
I want to merge #249 first as this will touch the same code and there will be lots of merge conflicts.
=> Fix case-insensitive comparison of channel names

Cargo.lock, term_input/Cargo.toml, term_input/src/lib.rs, termbox/src/lib.rs
Normally term_input is used with non-canonical input with VMIN=0 and
VTIME=0. On Linux in this mode stdin does not block (returns 0 when it's
not ready for reading, see [1] and [2]). However on WSL it doesn't work
that way and we have to set stdin to non-blocking mode to be able to do
`read(stdin)` without blocking.
We now set stdin to non-blocking mode when creating an `Input` and
restore the old flags when dropping it.
Fixes #269
[1]: https://www.gnu.org/software/libc/manual/html_node/Canonical-or-Not.html
[2]: https://www.gnu.org/software/libc/manual/html_node/Noncanonical-Input.html
=> term_input: Enable non-blocking mode

Cargo.lock
`Cargo.lock` must have not been committed since the `tiny` version was not
updated for the new release.
=> Lock file update

libtiny_tui/src/tui.rs, tiny/src/conn.rs
A bug appeared when I made the initial fix, where a new User tab is not highlighted due to the call order of `add_privmsg` and `set_tab_style`.
Closes #302
=> Fixed unnecessary tab creation on apply to target

crates/libtiny_tui/src/config.rs, crates/libtiny_tui/src/input_area/input_line.rs, crates/libtiny_tui/src/line_split.rs, crates/libtiny_tui/src/messaging.rs, crates/libtiny_tui/src/msg_area/line.rs, crates/libtiny_tui/src/msg_area/mod.rs, crates/libtiny_tui/src/tests/mod.rs, crates/libtiny_tui/src/tui.rs, crates/tiny/config.yml
Added Aligned UI, which can be turned on or off, and configured (currently only minimally).
Implementation details:
- The message area now has a `Layout` -- `Compact` (original) and `Aligned`.
- Each `Line` getting constructed  will have a type -- regular and aligned (`Msg` and `Aligned`, within `LineDataCache`). Not all message lines are aligned in the aligned ui (ex. topics)
- Drawing will consider the line type when drawing each line.
Small refactors are included.
Closes #169 and #299
=> Aligned UI

crates/libtiny_tui/src/exit_dialogue.rs, crates/libtiny_tui/src/lib.rs, crates/libtiny_tui/src/messaging.rs, crates/libtiny_tui/src/tui.rs
I often see users in the IRC channel wondering how to quit. They usually figure it out, but I think `/quit` is universal among tui IRC clients
=> Add /quit command

crates/tiny/src/utils.rs
Changed the /msg command to allow sending to any nick unless it begins
with '#'.
Fixes #324
=> /msg cmd, first char of nick

crates/libtiny_tui/src/tui.rs
This fixes a regression that I made when adding the /quit command.
Accidentally stopped processing commands if it was not in the
tui-specific commands, which causes all tiny client commands (cmd.rs) to
be ignored.
=> Fix broken commands

crates/tiny/src/ui.rs
It confused me for a night when I try to send `/msg NickServ REGISTER passwd email` and the tui always gives me "use `/connect <server>` to connect to a server" error.
But actually I have an connected server. so I got confused.
But if I send `/msg irc.libera.chat NickServ REGISTER passwd email`, it succeed!
After read the code, I found that this is not the right way to send a msg to `NickServ` (thought it works).
The only thing I need to do is switch from the default `mentions` tab to next tab.
and then, `/msg NickServ REGISTER passwd email` works as expected.
=> chore: more friendly error message

crates/libtiny_tui/src/msg_area/mod.rs, crates/libtiny_tui/src/tests/layout.rs, crates/libtiny_tui/src/tests/mod.rs, crates/libtiny_tui/src/tests/resize.rs
Closed previous PR (#320) since I found an issue with it while playing on my experimental branch. This solution is much simpler and behaves the way that irssi does. 
- Recalculate scroll value based on new total visible lines after a resize
- Moved tests and added new ones
Fixes #319
=> Add recalculating scroll on window resize

crates/libtiny_tui/src/msg_area/mod.rs, crates/libtiny_tui/src/tests/resize.rs
When you /clear the screen the total lines in the MsgArea gets cleared
and set to None. Then if you resize after that, we were unwrapping total
lines to recalculate the scroll amount and panicking.
We know the total line height is 0 after /clear so we now set total line
heights `Some(0)`.
Fixes #355
=> TUI: Fix line heights on `/resize`

crates/libtiny_client/src/state.rs, crates/libtiny_client/src/stream.rs, crates/libtiny_common/src/lib.rs, crates/libtiny_tui/src/lib.rs, crates/libtiny_tui/src/tui.rs, crates/libtiny_wire/src/formatting.rs, crates/libtiny_wire/src/lib.rs, crates/term_input/src/lib.rs, crates/tiny/src/cmd.rs
Fixes lints and warnings generated by rustc 1.65.0.
---
Creating a CL to test all targets.
=> Fix new lints and warnings

README.md, crates/libtiny_client/src/lib.rs, crates/libtiny_client/src/state.rs, crates/libtiny_common/src/lib.rs, crates/libtiny_tui/examples/chat.rs, crates/libtiny_tui/examples/tabs.rs, crates/libtiny_tui/src/lib.rs, crates/libtiny_tui/src/tui.rs, crates/libtiny_wire/src/lib.rs, crates/tiny/src/cmd.rs, crates/tiny/src/ui.rs
This pull request adds an optional message parameter to the `/quit` command to be sent to the connected servers as a reason for leaving.
This pull request was tested by using a tiny and a HexChat client, both connected to the same server.
Fixes #365.
=> Allow `/quit` with a message

crates/libtiny_tui/src/msg_area/line.rs, crates/termbox/src/lib.rs
added a fn for Line that updates its current style, OR'ing it with the attribute you want to set.
Had to add a few more bitmasks for Italic and Strikethrough as well.
This setup allows attributes to 'stack' easily, ie: receiving a message that's both bold and italic will show properly.
=> add formatting to termbox, render in tui (#364)

crates/libtiny_common/src/lib.rs, crates/libtiny_tui/src/config.rs, crates/libtiny_tui/src/lib.rs, crates/libtiny_tui/src/messaging.rs, crates/libtiny_tui/src/notifier.rs, crates/libtiny_tui/src/tab.rs, crates/libtiny_tui/src/tests/config.rs, crates/libtiny_tui/src/tests/mod.rs, crates/libtiny_tui/src/tui.rs, crates/tiny/config.yml, crates/tiny/src/cmd.rs, crates/tiny/src/config.rs, crates/tiny/src/conn.rs, crates/tiny/src/main.rs, crates/tiny/src/ui.rs
Added the ability to configure /ignore and /notify defaults for tabs.
The settings can be added under each chan, server or default section.
----
Overview:
- The most specific config will be the highest priority, i.e if you configure `ignore` under a chan then it will supersede the server's `ignore`, which will supersede the `ignore` under `defaults:`.
**Server tab:** server section -> defaults section -> hardcoded defaults (never ignore, notifier depends on conditional compilation, see `impl Default for Notifier`)
**Chan tabs:** chan section -> server section -> defaults section -> current setting on server tab (maybe someone toggled the setting manually)
**User tabs:** never ignore, notifier is always `Messages` (pre-existing behavior)
If acceptable, closes #118
=> Config to set /ignore and /notify

crates/libtiny_tui/src/exit_dialogue.rs, crates/libtiny_tui/src/input_area/mod.rs, crates/libtiny_tui/src/key_map.rs, crates/libtiny_tui/src/lib.rs, crates/libtiny_tui/src/messaging.rs, crates/libtiny_tui/src/tui.rs, crates/libtiny_tui/src/widget.rs
Allows the user to specify a config of this sort:
```yaml
key_map:
ctrl_d:
run_command: quit
```
Fixes #403
=> Support tiny commands in keymap config

Cargo.lock, crates/tiny/Cargo.toml, crates/tiny/src/cli.rs
clap is too heavyweight for what tiny needs. Replacing it with a simple hand-written parser reduces debug binary sizes a constant 14 MiB (!), and release binary sizes ~400 KiB.
- Default build, debug:
- Before: 73M
- After: 59M
- Diff: -14M, -29%
- Default build, release:
- Before: 6.4M
- After: 6.0M
- Diff: -0.4M, -6%
- Native TLS build, release:
- Before: 4.6M
- After: 4.2M
- Diff: -0.4M, -8%
Also saves ~10s build time and ~3s `cargo check` time.
Error messages and the help message is copied from what clap printed and modified.
=> Replace clap with a simple hand-written arg parser

.github/workflows/ci.yml, .github/workflows/release.yml
- Update Ubuntu from 20.04 to 22.04.
- Test statically linked builds in PRs to make sure we don't break the build when updating dependencies.
=> Update CI scripts

pkg/archlinux/PKGBUILD
This patch mirrors the PKGBUILD from AUR git, refactors, and improves it via the following commits. These commits are already present in the AUR git so anyone can test this script by installing tiny-irc-client-git.
Context: Prior to these commits, this script was not updated since 2021/11.  I reached out to the maintainers to suggest improvements. They mentioned they no longer use tiny then gave me the blessing to maintain the package myself.
=> PKGBUILD: refactor, improve, and sync changes with the version found in AUR git

Cargo.lock, crates/libtiny_client/Cargo.toml
Bumping tokio-rustls to exactly 0.24 upgrades ring to 0.17 without introducing breaking changes, despite having deprecated methods.
=> Upgrade ring to 0.17

CHANGELOG.md, crates/libtiny_tui/src/msg_area/line.rs, crates/libtiny_wire/src/formatting.rs
According to [1], a `0x03` without a color code following should reset the current bg and fg colors.
We can't reset just the colors without also resetting the formatting, for now reset colors + formatting.
Fixes #434.
=> Improve handling of IRC color code (0x03) without colors afterwards

CHANGELOG.md, crates/libtiny_tui/src/key_map.rs
I ran into this problem while trying to define a key binding for `ctrl_h`. Neither
did it work, nor did I get any error or warning. A quick search in the source
code revealed that the corresponding key strokes are represented as `Key::Backspace`
whereas the key binding itself is represented as `Key::Ctrl('h')`. I changed the
latter to be represented as `Key::Backspace` too, which fixes the issue. I included
a similar fix for `ctrl_i` (and also `ctrl_[`).
=> Added support for `ctrl_h` and `ctrl_i` in keymap config

crates/libtiny_client/examples/echo.rs, crates/libtiny_client/src/lib.rs, crates/libtiny_client/src/state.rs, crates/libtiny_wire/src/lib.rs, crates/tiny/config.yml, crates/tiny/src/cmd.rs, crates/tiny/src/config.rs, crates/tiny/src/main.rs
ZNC uses 'user' as a way to specify what network to connect to if there are several networks configured. E.g. myspecialuser/oftc or myspecialuser/libera
=> Add 'user' option for server
